import type { ResumeReviewResult } from "@/types/resume-review";

export function buildResumeOutlineMarkdown(
  result: ResumeReviewResult,
  jobTitle?: string,
): string {
  const lines: string[] = [
    "# Resume improvement checklist",
    "",
    jobTitle ? `**Target role:** ${jobTitle}` : null,
    `**Overall score:** ${result.overallScore}/100`,
    result.oneLineVerdict ? `**Verdict:** ${result.oneLineVerdict}` : null,
    "",
    "## Top fixes (do these first)",
    ...result.topFixes.map((fix, i) => `${i + 1}. ${fix}`),
    "",
  ].filter(Boolean) as string[];

  if (result.missingKeywords.length > 0) {
    lines.push("## ATS keywords to add", "");
    lines.push(result.missingKeywords.map((kw) => `- ${kw}`).join("\n"));
    lines.push("");
  }

  if (result.sections.length > 0) {
    lines.push("## Section feedback", "");
    for (const section of result.sections) {
      lines.push(`### ${section.name} (${section.score}/100)`);
      lines.push(section.summary);
      if (section.exampleFix) {
        lines.push("", `**Example fix:** ${section.exampleFix}`);
      }
      lines.push("");
    }
  }

  if (result.strongPoints.length > 0) {
    lines.push("## Keep these strengths", "");
    lines.push(result.strongPoints.map((pt) => `- ${pt}`).join("\n"));
    lines.push("");
  }

  lines.push("---", "Generated by ChampDSA resume review");
  return lines.join("\n");
}

export function downloadResumeOutline(
  result: ResumeReviewResult,
  jobTitle?: string,
) {
  const markdown = buildResumeOutlineMarkdown(result, jobTitle);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "resume-improvement-checklist.md";
  anchor.click();
  URL.revokeObjectURL(url);
}
