import type { JobLocation } from "@/types/job-search";

export type PortalLocationMaps = {
  naukri: string;
  indeed: string;
  foundit: string;
  shine: string;
  instahyre: string;
  hirist: string;
  wellfound: string;
  linkedin: string;
  internshala: string;
  reed: string;
  seek: string;
};

const LOCATION_PORTAL_SLUGS: Record<JobLocation, PortalLocationMaps> = {
  Bangalore: {
    naukri: "bangalore",
    indeed: "Bangalore, Karnataka",
    foundit: "Bengaluru / Bangalore",
    shine: "bangalore",
    instahyre: "bangalore",
    hirist: "bangalore",
    wellfound: "Bangalore",
    linkedin: "Bangalore, Karnataka, India",
    internshala: "bangalore",
    reed: "london",
    seek: "sydney",
  },
  Hyderabad: {
    naukri: "hyderabad",
    indeed: "Hyderabad, Telangana",
    foundit: "Hyderabad / Secunderabad",
    shine: "hyderabad",
    instahyre: "hyderabad",
    hirist: "hyderabad",
    wellfound: "Hyderabad",
    linkedin: "Hyderabad, Telangana, India",
    internshala: "hyderabad",
    reed: "london",
    seek: "sydney",
  },
  Pune: {
    naukri: "pune",
    indeed: "Pune, Maharashtra",
    foundit: "Pune",
    shine: "pune",
    instahyre: "pune",
    hirist: "pune",
    wellfound: "Pune",
    linkedin: "Pune, Maharashtra, India",
    internshala: "pune",
    reed: "london",
    seek: "sydney",
  },
  Mumbai: {
    naukri: "mumbai",
    indeed: "Mumbai, Maharashtra",
    foundit: "Mumbai",
    shine: "mumbai",
    instahyre: "mumbai",
    hirist: "mumbai",
    wellfound: "Mumbai",
    linkedin: "Mumbai, Maharashtra, India",
    internshala: "mumbai",
    reed: "london",
    seek: "sydney",
  },
  Chennai: {
    naukri: "chennai",
    indeed: "Chennai, Tamil Nadu",
    foundit: "Chennai",
    shine: "chennai",
    instahyre: "chennai",
    hirist: "chennai",
    wellfound: "Chennai",
    linkedin: "Chennai, Tamil Nadu, India",
    internshala: "chennai",
    reed: "london",
    seek: "sydney",
  },
  Delhi: {
    naukri: "delhi-ncr",
    indeed: "Delhi",
    foundit: "Delhi",
    shine: "delhi",
    instahyre: "delhi-ncr",
    hirist: "delhi",
    wellfound: "New Delhi",
    linkedin: "New Delhi, Delhi, India",
    internshala: "delhi",
    reed: "london",
    seek: "sydney",
  },
  Noida: {
    naukri: "noida",
    indeed: "Noida, Uttar Pradesh",
    foundit: "Noida",
    shine: "noida",
    instahyre: "noida",
    hirist: "noida",
    wellfound: "Noida",
    linkedin: "Noida, Uttar Pradesh, India",
    internshala: "noida",
    reed: "london",
    seek: "sydney",
  },
  Gurgaon: {
    naukri: "gurgaon",
    indeed: "Gurgaon, Haryana",
    foundit: "Gurgaon",
    shine: "gurgaon",
    instahyre: "gurgaon",
    hirist: "gurgaon-gurugram",
    wellfound: "Gurgaon",
    linkedin: "Gurugram, Haryana, India",
    internshala: "gurgaon",
    reed: "london",
    seek: "sydney",
  },
  Ahmedabad: {
    naukri: "ahmedabad",
    indeed: "Ahmedabad, Gujarat",
    foundit: "Ahmedabad",
    shine: "ahmedabad",
    instahyre: "ahmedabad",
    hirist: "ahmedabad",
    wellfound: "Ahmedabad",
    linkedin: "Ahmedabad, Gujarat, India",
    internshala: "ahmedabad",
    reed: "london",
    seek: "sydney",
  },
  "Gift City": {
    naukri: "gandhinagar",
    indeed: "Gandhinagar, Gujarat",
    foundit: "Gandhinagar",
    shine: "gandhinagar",
    instahyre: "gandhinagar",
    hirist: "gandhinagar",
    wellfound: "Gandhinagar",
    linkedin: "Gandhinagar, Gujarat, India",
    internshala: "gandhinagar",
    reed: "london",
    seek: "sydney",
  },
  Kolkata: {
    naukri: "kolkata",
    indeed: "Kolkata, West Bengal",
    foundit: "Kolkata",
    shine: "kolkata",
    instahyre: "kolkata",
    hirist: "kolkata",
    wellfound: "Kolkata",
    linkedin: "Kolkata, West Bengal, India",
    internshala: "kolkata",
    reed: "london",
    seek: "sydney",
  },
  Chandigarh: {
    naukri: "chandigarh",
    indeed: "Chandigarh",
    foundit: "Chandigarh",
    shine: "chandigarh",
    instahyre: "chandigarh",
    hirist: "chandigarh",
    wellfound: "Chandigarh",
    linkedin: "Chandigarh, India",
    internshala: "chandigarh",
    reed: "london",
    seek: "sydney",
  },
  Jaipur: {
    naukri: "jaipur",
    indeed: "Jaipur, Rajasthan",
    foundit: "Jaipur",
    shine: "jaipur",
    instahyre: "jaipur",
    hirist: "jaipur",
    wellfound: "Jaipur",
    linkedin: "Jaipur, Rajasthan, India",
    internshala: "jaipur",
    reed: "london",
    seek: "sydney",
  },
  Kochi: {
    naukri: "kochi",
    indeed: "Kochi, Kerala",
    foundit: "Kochi",
    shine: "kochi",
    instahyre: "kochi",
    hirist: "cochin-kochi",
    wellfound: "Kochi",
    linkedin: "Kochi, Kerala, India",
    internshala: "kochi",
    reed: "london",
    seek: "sydney",
  },
  Indore: {
    naukri: "indore",
    indeed: "Indore, Madhya Pradesh",
    foundit: "Indore",
    shine: "indore",
    instahyre: "indore",
    hirist: "indore",
    wellfound: "Indore",
    linkedin: "Indore, Madhya Pradesh, India",
    internshala: "indore",
    reed: "london",
    seek: "sydney",
  },
  "Remote India": {
    naukri: "india",
    indeed: "India",
    foundit: "India",
    shine: "all-india",
    instahyre: "remote",
    hirist: "india",
    wellfound: "India",
    linkedin: "India",
    internshala: "work-from-home",
    reed: "london",
    seek: "sydney",
  },
  London: {
    naukri: "london",
    indeed: "London",
    foundit: "London",
    shine: "london",
    instahyre: "london",
    hirist: "london",
    wellfound: "London",
    linkedin: "London, England, United Kingdom",
    internshala: "london",
    reed: "london",
    seek: "sydney",
  },
  Manchester: {
    naukri: "manchester",
    indeed: "Manchester",
    foundit: "Manchester",
    shine: "manchester",
    instahyre: "manchester",
    hirist: "manchester",
    wellfound: "Manchester",
    linkedin: "Manchester, England, United Kingdom",
    internshala: "manchester",
    reed: "manchester",
    seek: "sydney",
  },
  Sydney: {
    naukri: "sydney",
    indeed: "Sydney NSW",
    foundit: "Sydney",
    shine: "sydney",
    instahyre: "sydney",
    hirist: "sydney",
    wellfound: "Sydney",
    linkedin: "Sydney, New South Wales, Australia",
    internshala: "sydney",
    reed: "london",
    seek: "sydney",
  },
  Melbourne: {
    naukri: "melbourne",
    indeed: "Melbourne VIC",
    foundit: "Melbourne",
    shine: "melbourne",
    instahyre: "melbourne",
    hirist: "melbourne",
    wellfound: "Melbourne",
    linkedin: "Melbourne, Victoria, Australia",
    internshala: "melbourne",
    reed: "london",
    seek: "melbourne",
  },
  "Remote Global": {
    naukri: "india",
    indeed: "Remote",
    foundit: "Remote",
    shine: "all-india",
    instahyre: "remote",
    hirist: "india",
    wellfound: "Remote",
    linkedin: "Worldwide",
    internshala: "work-from-home",
    reed: "london",
    seek: "sydney",
  },
};

export function pickPrimaryLocation(locations: JobLocation[]): JobLocation {
  if (locations.length === 0) return "Bangalore";
  const onSite = locations.filter(
    (l) => l !== "Remote India" && l !== "Remote Global",
  );
  return onSite[0] ?? locations[0] ?? "Bangalore";
}

export function getPortalLocations(location: JobLocation): PortalLocationMaps {
  return LOCATION_PORTAL_SLUGS[location];
}

export function slugifySegment(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}
